---
title: "DCS 520 10/6"
author: "Josh Howard"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
```

```{r}
(state <- read_csv("state.csv", col_names=TRUE))
```

```{r}
kable(state[1:5,], caption = "Murder Rate by States(per 100,000")
```
```{r}
mean(state$Population)
mean(state[['Population']])
```
Weighted Mean Formula
$$\overline{x}_w=\frac{\sum_{i=1}^n w_i x_i}{\sum_{i=1}^n w_i}$$
Mean Formula
$$\overline{x}=\frac{1}{n}\sum_{i=1}^n x_i$$
```{r}
mean(state$Murder.Rate)
```
```{r}
weighted.mean(state$Murder.Rate, w = state$Population)
```
n is even median:
$$\text{Median}(x) = \frac{ x_{n/2} + x_{n/2+1} }{2}$$
```{r}
median(state$Murder.Rate)
```

```{r}
library(matrixStats)
```
```{r}
weightedMedian(state$Murder.Rate, w = state$Population)
```
```{r}
state%>%ggplot()+
  geom_histogram(aes(Murder.Rate), bins = 15)
```
```{r}
state%>%arrange(desc(Murder.Rate))
```
```{r}
quantile(state$Murder.Rate, c(0.1, 0.25, 0.5, 0.98))
```
Trimmed Mean Formula:
$$\overline{X}_{trm}=\frac{\sum_{i=p+1}^{n-p}x_i}{n-2p}$$
```{r}
mean(state$Murder.Rate, trim = 2/50)
```

